[build]
builder = "NIXPACKS"
buildCommand = "CI=false yarn install && yarn build"

[deploy]
startCommand = "npx serve -s build -l ${PORT:-3000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
